# Generated by Django 4.2.9 on 2024-01-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=255)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('is_pleasurable', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(default=1)),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
