# Generated by Django 4.2.9 on 2024-01-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='frequency',
            new_name='frequency_days',
        ),
    ]
